# Generated by Django 5.1.4 on 2025-11-18 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Хичээлийн нэр')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Хичээлийн код')),
            ],
            options={
                'verbose_name': 'Хичээл',
                'verbose_name_plural': 'Хичээлүүд',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('latitude', models.FloatField(verbose_name='Өргөрөг')),
                ('longitude', models.FloatField(verbose_name='Уртраг')),
                ('radius_m', models.PositiveIntegerField(default=100, verbose_name='Радиус (м)')),
            ],
            options={
                'verbose_name': 'Байршил',
                'verbose_name_plural': 'Байршлууд',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50, unique=True, verbose_name='Оюутны код')),
                ('full_name', models.CharField(max_length=200, verbose_name='Нэр')),
            ],
            options={
                'verbose_name': 'Оюутан',
                'verbose_name_plural': 'Оюутнууд',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Нэр')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Багш',
                'verbose_name_plural': 'Багш нар',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(choices=[('I', '08:00-09:30'), ('II', '09:40-11:10'), ('III', '11:20-12:50'), ('IV', '13:20-14:50'), ('V', '15:00-16:30'), ('VI', '16:40-18:10'), ('VII', '18:20-19:50'), ('VIII', '20:00-21:30')], max_length=20, verbose_name='Цаг')),
                ('form', models.CharField(choices=[('Lecture', 'Лекц'), ('Seminar', 'Семинар'), ('Lab', 'Лаборатори'), ('Practice', 'Дадлага')], max_length=20, verbose_name='Төрөл')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Token')),
                ('session_date', models.DateField(auto_now_add=True, verbose_name='Хичээл орсон өдөр')),
                ('is_active', models.BooleanField(default=True, verbose_name='QR идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.course', verbose_name='Хичээл')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irts_app.location', verbose_name='Байршил')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.teacherprofile', verbose_name='Багш')),
            ],
            options={
                'verbose_name': 'Хичээлийн сесс',
                'verbose_name_plural': 'Хичээлийн сессүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF')], max_length=10, verbose_name='Формат')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irts_app.classsession', verbose_name='Хичээлийн сесс')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.course', verbose_name='Хичээл')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.teacherprofile', verbose_name='Багш')),
            ],
            options={
                'verbose_name': 'Ирцийн тайлан',
                'verbose_name_plural': 'Ирцийн тайлангууд',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Даваа'), (1, 'Мягмар'), (2, 'Лхагва'), (3, 'Пүрэв'), (4, 'Баасан'), (5, 'Бямба'), (6, 'Ням')], verbose_name='Гараг')),
                ('start_time', models.CharField(choices=[('I', '08:00-09:30'), ('II', '09:40-11:10'), ('III', '11:20-12:50'), ('IV', '13:20-14:50'), ('V', '15:00-16:30'), ('VI', '16:40-18:10'), ('VII', '18:20-19:50'), ('VIII', '20:00-21:30')], max_length=20, verbose_name='Цаг')),
                ('form', models.CharField(choices=[('Lecture', 'Лекц'), ('Seminar', 'Семинар'), ('Lab', 'Лаборатори'), ('Practice', 'Дадлага')], max_length=20, verbose_name='Хичээлийн төрөл')),
                ('week_start', models.DateField(verbose_name='Долоо хоногийн эхлэх өдөр')),
                ('week_end', models.DateField(verbose_name='Долоо хоногийн дуусах өдөр')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.course', verbose_name='Хичээл')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irts_app.location', verbose_name='Байршил')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.teacherprofile', verbose_name='Багш')),
            ],
            options={
                'verbose_name': 'Долоо хоногийн хуваарь',
                'verbose_name_plural': 'Долоо хоногийн хуваарь',
                'ordering': ['week_start', 'day_of_week', 'start_time'],
                'unique_together': {('course', 'teacher', 'day_of_week', 'start_time', 'week_start')},
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='week_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irts_app.weeklyschedule', verbose_name='Долоо хоногийн хуваарь'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.course', verbose_name='Хичээл')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.student', verbose_name='Оюутан')),
            ],
            options={
                'verbose_name': 'Бүртгэл',
                'verbose_name_plural': 'Бүртгэлүүд',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгүүлсэн цаг')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('success', models.BooleanField(default=False, verbose_name='Ирсэн эсэх')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Тэмдэглэл')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.classsession', verbose_name='Хичээл')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irts_app.student', verbose_name='Оюутан')),
            ],
            options={
                'verbose_name': 'Ирц',
                'verbose_name_plural': 'Ирцүүд',
                'ordering': ['-timestamp'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
